#!/bin/bash
# GitHub 克隆辅助脚本 - 适用于阿里云境内服务器

echo "=== GitHub 克隆解决方案 ==="
echo ""
echo "由于网络限制，推荐以下方案："
echo ""
echo "【方案一】如果你有代理服务器，配置 Git 代理："
echo "  git config --global http.proxy http://代理地址:端口"
echo "  git config --global https.proxy https://代理地址:端口"
echo ""
echo "【方案二】使用本地电脑下载后上传到服务器："
echo "  1. 在本地电脑访问：https://github.com/JNUZXF/stock_agent"
echo "  2. 点击 Code -> Download ZIP"
echo "  3. 使用 scp 上传到服务器："
echo "     scp stock_agent-main.zip root@你的服务器IP:/home/"
echo "  4. 在服务器上解压：unzip stock_agent-main.zip && mv stock_agent-main stock_agent"
echo ""
echo "【方案三】使用 Gitee 导入 GitHub 项目（推荐）："
echo "  1. 访问 https://gitee.com"
echo "  2. 创建仓库 -> 导入 -> 从 GitHub 导入"
echo "  3. 输入：https://github.com/JNUZXF/stock_agent"
echo "  4. 导入后使用：git clone https://gitee.com/你的用户名/stock_agent.git"
echo ""
echo "【方案四】配置 SSH 密钥并使用 SSH 方式克隆（如果已配置）："
echo "  git clone git@github.com:JNUZXF/stock_agent.git"
echo ""
