#!/bin/bash
# 利用新加坡服务器克隆 GitHub 项目的方案脚本

SINGAPORE_IP="47.237.167.77"
CURRENT_SERVER_IP=$(hostname -I | awk '{print $1}')

echo "=== 利用新加坡服务器 (${SINGAPORE_IP}) 克隆 GitHub 项目 ==="
echo ""
echo "【方案一】在新加坡服务器克隆后同步到当前服务器（推荐）"
echo ""
echo "步骤："
echo "1. 登录新加坡服务器："
echo "   ssh root@${SINGAPORE_IP}"
echo ""
echo "2. 在新加坡服务器上克隆项目："
echo "   cd /tmp"
echo "   git clone https://github.com/JNUZXF/stock_agent.git"
echo "   tar -czf stock_agent.tar.gz stock_agent/"
echo ""
echo "3. 从当前服务器拉取文件（在新加坡服务器上执行）："
echo "   # 方法 A：使用 scp（从阿里云服务器执行）"
echo "   scp -r root@${SINGAPORE_IP}:/tmp/stock_agent.tar.gz /home/"
echo "   cd /home && tar -xzf stock_agent.tar.gz"
echo ""
echo "   # 方法 B：使用 rsync（从阿里云服务器执行）"
echo "   rsync -avz root@${SINGAPORE_IP}:/tmp/stock_agent/ /home/stock_agent/"
echo ""
echo "【方案二】在新加坡服务器搭建 HTTP 代理"
echo ""
echo "1. 在新加坡服务器上安装并启动代理（如使用 tinyproxy）："
echo "   ssh root@${SINGAPORE_IP}"
echo "   yum install -y tinyproxy  # CentOS/RHEL"
echo "   # 或 apt-get install -y tinyproxy  # Ubuntu/Debian"
echo "   echo 'Allow ${CURRENT_SERVER_IP}' >> /etc/tinyproxy/tinyproxy.conf"
echo "   systemctl start tinyproxy"
echo ""
echo "2. 在当前服务器（阿里云）配置 Git 使用代理："
echo "   git config --global http.proxy http://${SINGAPORE_IP}:8888"
echo "   git config --global https.proxy http://${SINGAPORE_IP}:8888"
echo "   git clone https://github.com/JNUZXF/stock_agent.git"
echo ""
echo "【方案三】在新加坡服务器搭建 SOCKS5 代理（使用 ss/ssr/v2ray）"
echo "   需要安装相应的代理软件，配置更复杂但更安全"
echo ""
